[package]
name = "minirust-api"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "MiniRust REST API"

[dependencies]
axum = { workspace = true, features = ["multipart"] }
axum-extra.workspace = true
minirust-config.workspace = true
minirust-core.workspace = true
minirust-database.workspace = true
minirust-locales.workspace = true
minirust-observability.workspace = true
minirust-services.workspace = true
lettre.workspace = true
serde.workspace = true
serde_json = "1"
tokio.workspace = true
tower-http.workspace = true
uuid.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
testcontainers.workspace = true
tower.workspace = true
sqlx.workspace = true
